<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>BOS.API</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BOS.Application\BOS.Application.csproj" />
    <ProjectReference Include="..\BOS.Infrastructure\BOS.Infrastructure.csproj" />
  </ItemGroup>
</Project>
