<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>BOS.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <NoWarn>CA1707</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BOS.Core\BOS.Core.csproj" />
    <ProjectReference Include="..\..\src\BOS.Domain\BOS.Domain.csproj" />
    <ProjectReference Include="..\..\src\BOS.Application\BOS.Application.csproj" />
    <ProjectReference Include="..\..\src\BOS.Infrastructure\BOS.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\BOS.Api\BOS.Api.csproj" />
    <ProjectReference Include="..\..\src\BOS.Modules\BOS.Modules.csproj" />
  </ItemGroup>

</Project>
